name: Publish code/api to Dockerhub

defaults:
  run:
    shell: bash
    working-directory: 'code/api/'

on:
  push:
    branches:
      - main
    paths:
      - 'code/api/**'
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies for Python project  
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Linting project with flake8
        run: |
          ls -la
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: 'code/api/'
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ecs-api-service:1.0.0
          cache-from: 'type=registry,ref=user/app:1.0.0'
          cache-to: 'type=inline'